language: objective-c
 
#branches:
# only:
# - master
 
xcode_project: MZOpenWeatherApp-Swift.xcodeproj
xcode_scheme: MZOpenWeatherApp-Swift
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
 
script:
- xcodebuild clean build -project MZOpenWeatherApp-Swift/MZOpenWeatherApp-Swift.xcodeproj -scheme MZOpenWeatherApp-Swift CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
- xctool test -project MZOpenWeatherApp-Swift/MZOpenWeatherApp-Swift.xcodeproj -scheme MZOpenWeatherApp-Swift -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
