language: objective-c
 
#branches:
# only:
# - master
 
xcode_project: MZOpenWeatherApp-Swift.xcodeproj
xcode_scheme: MZOpenWeatherApp-Swift
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3

install:
- brew update
- brew reinstall xctool

script:
- xcodebuild clean build -project MZOpenWeatherApp-Swift/MZOpenWeatherApp-Swift.xcodeproj -scheme MZOpenWeatherApp-Swift CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
#- xctool test -project MZOpenWeatherApp-Swift/MZOpenWeatherApp-Swift.xcodeproj -scheme MZOpenWeatherApp-Swift -sdk iphonesimulator9.3 CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
- xcodebuild test -project MZOpenWeatherApp-Swift/MZOpenWeatherApp-Swift.xcodeproj -scheme MZOpenWeatherApp-Swift -destination 'platform=iOS Simulator,name=iPhone 4s,OS=9.3' 
    #-destination 'platform=iOS Simulator,name=iPhone 5,OS=9.3' -destination 'platform=iOS Simulator,name=iPhone 5s,OS=9.3'